# Generated by Django 2.2.6 on 2020-02-12 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=254)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('date', models.DateField(unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('init_data', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
    ]
