# Generated by Django 2.2.10 on 2020-03-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='rx_read',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traffic',
            name='tx_read',
            field=models.BigIntegerField(default=0),
        ),
    ]
